#include "knowledge_base.h"
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QRegularExpression>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QStandardPaths>
#include <algorithm>

KnowledgeBase::KnowledgeBase() {
    m_path=QStandardPaths::writableLocation(QStandardPaths::AppDataLocation)+"/knowledge.json";
    QDir().mkpath(QFileInfo(m_path).absolutePath()); load(); addSeedKnowledge();
}
void KnowledgeBase::load() {
    QFile f(m_path);if(!f.open(QIODevice::ReadOnly))return;auto doc=QJsonDocument::fromJson(f.readAll());
    for(auto v:doc.array()){auto o=v.toObject();if(!o.value("title").toString().isEmpty())m_entries.append({o.value("title").toString(),o.value("text").toString(),o.value("tags").toString()});}
}
bool KnowledgeBase::save(QString *error) const {
    QJsonArray a;for(const auto &e:m_entries)a.append(QJsonObject{{"title",e.title},{"text",e.text},{"tags",e.tags}});
    QFile f(m_path);if(!f.open(QIODevice::WriteOnly)){if(error)*error=f.errorString();return false;}if(f.write(QJsonDocument(a).toJson())<0){if(error)*error=f.errorString();return false;}return true;
}
bool KnowledgeBase::add(const KnowledgeEntry &e,QString *error) { if(e.title.trimmed().isEmpty()||e.text.trimmed().isEmpty()){if(error)*error="Нужны заголовок и текст знания.";return false;}m_entries.append(e);if(!save(error)){m_entries.removeLast();return false;}return true; }
void KnowledgeBase::addSeedKnowledge() {
    const QVector<KnowledgeEntry> defaults={
        {"Безопасное изменение базы TrinityCore","Перед UPDATE, DELETE или импортом создайте резервную копию и тестируйте на отдельной базе. Используйте транзакции, WHERE по entry/guid и SELECT-проверку до изменения. Схемы world/auth/characters и имена полей различаются между ветками TrinityCore.","mysql trinitycore sql backup migration"},
        {"Разбор ошибок SQL","Сначала проверьте точное имя таблицы и столбца через SHOW CREATE TABLE или DESCRIBE. При ошибке foreign key добавляйте родительскую запись первой. При duplicate entry проверяйте существующий entry. Не заменяйте данные REPLACE INTO без понимания каскадных эффектов.","mysql error sql schema"},
        {"SmartAI: методика","SmartAI связывает source_type, entryorguid, id, link, event_type, action_type и target_type. Для существа сначала определите, template это или конкретный spawn GUID. Проверяйте доступность типов в версии ядра и выполняйте DELETE только по точному source_type и entryorguid перед INSERT.","smartai creature npc scripting"},
        {"C++ TrinityCore: методика","Для серверных скриптов сверяйте API с исходниками именно вашей ветки. Изолируйте логику, валидируйте указатели и GUID, не выполняйте тяжёлые SQL-запросы в частых обработчиках. После изменений пересоберите ядро и изучите полный лог компилятора, начиная с первой ошибки.","c++ core script compile"},
        {"World of Warcraft: серверные сущности","В WoW игрок взаимодействует с существами (NPC/creature), игровыми объектами, предметами, заданиями, заклинаниями, картами и зонами. Подземелья и рейды обычно связаны с map/instance, доступом, encounter и spawn-данными. Клиентские ID и описание не доказывают наличие одинакового поля в серверной БД: всегда сверяйте вашу схему и build.","wow gameplay npc item quest dungeon raid instance map"},
        {"NPC, квесты и предметы: проверка","NPC template описывает тип существа, а spawn — размещённый экземпляр. Предмет обычно начинается с item template и связей loot/vendor/quest. Квест проверяйте по template, objectives, rewards, relations и conditions; точные таблицы зависят от ветки ядра. Проверяйте изменения в игре тестовым персонажем.","npc creature item quest loot vendor spawn"},
        {"Wowhead и DB2","Wowhead полезен для идентификаторов и игрового описания, но не заменяет структуру вашей базы или DB2 данного build. Сверяйте client build, DB2-таблицу, SQL schema и данные выбранной версии ядра. Соблюдайте условия источника данных.","wowhead db2 client build"},
        {"Nordrassil Core 7.3.5","Nordrassil — Legion-форк TrinityCore под клиент 7.3.5.26972. Реалм = bnetserver (порт 1119), ядро = worldserver (8085/8086). Аккаунт: в консоли ядра bnetaccount create email@local password, затем account set gmlevel. Базы: auth, characters, world, hotfixes. Wago DB2 идёт в hotfixes, не в world.","nordrassil legion 7.3.5 bnetserver worldserver hotfix"},
        {"Зависание ядра после входа","После логина worldserver грузит персонажа (characters.*) и грид карты (maps/vmaps/mmaps). Зависание без закрытия окна — обычно SQL-лок, отсутствующие mmap или скрипт инстанса. Последняя строка лога ДО зависания важнее ошибки рестарта. На рестарте «address already in use» / bind failed значит старый процесс жив: снимите worldserver.exe в диспетчере, проверьте netstat по 8085/1119, подождите MySQL. Смотрите Server.log, Errors.log, Logs/Crashes.","worldserver freeze hang crash bind port already in use mmap"},
        {"Таблицы NPC и движение","creature_template — тип NPC (entry). creature — спавн (guid) на карте. MovementType: 0 стоит, 1 бродит (spawndist>0), 2 идёт по waypoint. creature_addon.path_id ссылается на waypoint_data.id. Точки: waypoint_data (id, point, x, y, z, delay). smart_scripts — события, не сам маршрут. AIName=SmartAI если нужен SAI. На 3.3.5a в smart_scripts нет event_param5.","npc creature waypoint path_id movementtype smart_scripts addon"},
        {"event_param5 и схема SmartAI","Unknown column event_param5: TrinityCore 3.3.5a имеет event_param1–4. event_param5 есть в более новых ядрах. Читайте SHOW COLUMNS FROM smart_scripts своей базы, не копируйте SQL с 7.3.5 в 3.3.5a.","event_param5 smart_scripts unknown column 3.3.5"},
        {"RAM worldserver","Цель 8→4 ГБ: PreloadAllNonInstancedMapGrids/BaseMapLoadAllGrids/InstanceMapLoadAllGrids/BattlegroundMapLoadAllGrids=0, GridUnload=1, GridCleanUpDelay=60000, Visibility.Distance.Continents=70. mmap/vmap не отключать. Сборка Release. MySQL innodb_buffer_pool_size=1G если на той же машине. Кнопка «Снизить RAM ядра». Ниже ~3–4 ГБ Legion 7.3.5 обычно не опускается из‑за DB2/hotfixes.","ram memory preload gridunload mmap worldserver.conf 4gb 8gb"},
        {"Ядра 7.3.5–12.x: ID SmartAI не переносимы","Базовые действия SmartAI (TALK=1, CAST=11, SUMMON_CREATURE=12, ADD_AURA=75, WP_START=53, MOVE_TO_POS=69, SET_RUN=59, TELEPORT=62, EVADE=24, FOLLOW=29, SET_PHASE/RANDOM_PHASE=30, ATTACK_START=49) совпадают между Nordrassil 7.3.5 и TrinityCore master. НО расширенные диапазоны и часть событий различаются: DISTANCE_CREATURE = 79 в 7.3.5 и 75 в master; COUNTER_SET = 80 в 7.3.5 и 77 в master. В 7.3.5 событие 2% HP называется с опечаткой SMART_EVENT_HEALT_PCT, в master исправлено на HEALTH_PCT (ID тот же 2). В Nordrassil есть кастомные действия 161-234 (SET_POWER_TYPE, CAST_SPELL_OFFSET, STORE_VARIABLE_DECIMAL, PLAY_SPELL_VISUAL_KIT), которых нет в master. Никогда не копируй smart_scripts между ветками без сверки ID по SmartScriptMgr.h конкретного ядра.","smartai smart_scripts id core 7.3.5 master retail несовместимость nordrassil trinitycore"},
        {"TrinityCore master (retail 11.x/12.x): профиль","TrinityCore master — retail-ветка (11.x/12.x), moving target. Базы: auth, characters, world, hotfixes. Реалм = bnetserver. SmartAI: 92 события (макс 91), 161 действие (макс 160), 32 цели. Команд .reload = 98. Перезагрузка путей: .reload waypoint_path (не waypoint_data). Есть scene_template, criteria_data, rbac, quest_greeting, quest_locale, item_random_bonus_list_template, creature_movement_override. Локали квестов: quest_locale (не quest_template_locale). Официальных веток 7.3.5/8.x/9.x/10.x в репозитории TrinityCore нет — только 3.3.5, cata_classic, wotlk_classic, master.","trinitycore master retail 11.x 12.x waypoint_path scene_template quest_locale reload"},
        {"Nordrassil Core 7.3.5: профиль и отличия лута","Nordrassil — Legion-форк TrinityCore под клиент 7.3.5.26972. Базы: auth, characters, world, hotfixes. Реалм = bnetserver (1119), ядро = worldserver (8085/8086). SmartAI: 82 события (макс 80), 163 действия (макс 234), 33 цели. Команд .reload = 117. Лут КАСТОМНЫЙ (LootMgr.cpp): groupid>0 = ровно один предмет из группы (поведения groupid>8 НЕТ); shared=1 в creature_loot_template = доп. проверка 0.5% (не общий на группу); отрицательный item = валюта; shared есть только у creature_loot_template. Есть zone/world/luck/personal_loot_template, waypoint_data, waypoint_scripts, script_waypoint, creature_template_outfits, phasedefinitions, eventobject. Тексты квестов в quest_template_locale (12 локалей, ruRU есть). Статы предметов в hotfixes.item_sparse.","nordrassil 7.3.5 legion loot groupid shared zone_loot personal_loot quest_template_locale item_sparse"},
        {"reload-команды: 7.3.5 vs master","Только в 7.3.5: zone_loot_template, world_loot_template, luck_loot_template, waypoint_data, waypoint_scripts, script_waypoint, creature_template_outfits, phasedefinitions, scenario_data, conversation, creature_area. Только в master: waypoint_path, creature_movement_override, item_random_bonus_list_template, quest_greeting, quest_locale, scene_template, criteria_data, rbac, support, trainer, spell_script_names, *_locale таблицы. Общие: creature_loot_template, reference_loot_template, gameobject_loot_template, item_loot_template, conditions, quest_template, creature_queststarter/questender, creature_template, creature_text, gossip_menu, smart_scripts, creature_summon_groups, spell_proc, spell_linked_spell, spell_target_position, access_requirement, item. В 7.3.5 .reload quest_template через LoadQuests() тянет сразу quest_objectives, quest_template_addon, quest_details, quest_offer_reward, quest_request_items. Тексты — отдельной .reload locales_quest (7.3.5) / quest_locale (master).","reload waypoint_path waypoint_data quest_locale locales_quest zone_loot_template master 7.3.5"},
        {"Legion: новый предмет/спелл требует патч клиента","В Legion (7.3.5) и retail данные предметов и спеллов размазаны: серверная часть в world (item_template, creature_template_spell), а имя/ItemLevel/статы/сокеты — в hotfixes (item_sparse, item_bonus, item_effect, scaling_stat_distribution, curve). В дампе Nordrassil item_bonus/scaling_stat_distribution/curve ПУСТЫЕ — основной объём клиент берёт из своего DB2/DBCache. Вывод: новый предмет или спелл нельзя сделать одним SQL — нужна правка БД (world + hotfixes) И патч клиентских DB2 (item.db2, item-sparse.db2, spell.db2, spell-effect.db2) или DBCache. Для ПРАВКИ существующего предмета часто достаточно item_template + item_sparse.","legion item spell hotfixes item_sparse db2 dbcache client patch новый предмет спелл"},
        {"Схемы БД: квесты и пути по веткам","Квесты: 7.3.5 = quest_template + quest_objectives + quest_template_locale; master = quest_template + quest_objectives + quest_locale + quest_greeting. Типы целей quest_objectives.Type (QuestDef.h): 0=MONSTER, 1=ITEM, 2=GAMEOBJECT, 3=TALKTO, 4=CURRENCY, 5=LEARNSPELL, 8=MONEY, 9=PLAYERKILLS, 10=AREATRIGGER, 14=COMPLETE_CRITERIA_TREE, 15=TASK_IN_ZONE. Флаги: 0x01 TRACKED_ON_MINIMAP, 0x02 SEQUENCED, 0x04 OPTIONAL, 0x08 HIDDEN. Пути: 7.3.5 = waypoints (path ID) + waypoint_data (GUID) + script_waypoint (entry); master = waypoint_path. Привязка пути: creature_addon.path_id / creature_template_addon.path_id. MovementType: 0=нет, 1=блуждание, 2=путь.","quest_template quest_objectives quest_locale waypoint_path waypoint_data path_id movementtype схема"},
        {"SQL-шаблон: квест (Nordrassil 7.3.5)","Создание квеста в Legion 7.3.5 = 3 таблицы. (1) quest_template — механика: ID, MinLevel, QuestLevel, QuestType=2, AllowableClasses, Flags, RewardXPTitle и пр. ВАЖНО: LogTitle/LogDescription/QuestDescription в quest_template хранят ID из broadcast_text, НЕ текст. (2) quest_objectives — цели: INSERT INTO quest_objectives (ID,QuestID,Type,StorageIndex,ObjectID,Amount,Flags,Flags2,TaskStep,Description,VerifiedBuild) VALUES (@OBJ_ID,@QUEST,0,0,@MOB,5,0,0,0,'',0); Type 0=MONSTER,1=ITEM,2=GAMEOBJECT,3=TALKTO; ID цели глобально уникален. (3) quest_template_locale — читаемый текст: INSERT INTO quest_template_locale (ID,locale,LogTitle,LogDescription,QuestDescription,AreaDescription,PortraitGiverText,PortraitGiverName,PortraitTurnInText,PortraitTurnInName,QuestCompletionLog,VerifiedBuild) VALUES (@QUEST,'ruRU','Название','Кратко','Полное описание','','','','','','',0). Выдача/сдача: creature_queststarter (id=@NPC_START, quest=@QUEST) и creature_questender (id=@NPC_END, quest=@QUEST). Свободный ID: SELECT MAX(ID)+10 FROM quest_template. После: .reload quest_template и .reload locales_quest.","quest квест quest_template quest_objectives quest_template_locale creature_queststarter creature_questender sql шаблон 7.3.5 nordrassil"},
        {"SQL-шаблон: лут существа (Nordrassil 7.3.5, кастомный LootMgr)","Лут в Nordrassil КАСТОМНЫЙ (LootMgr.cpp), не как сток TC. Независимый дроп: INSERT INTO creature_loot_template (entry,item,ChanceOrQuestChance,lootmode,groupid,mincountOrRef,maxcount,shared) VALUES (@ENTRY,@ITEM,@CHANCE,0,0,1,1,0). groupid=0 = независимый ролл каждого предмета. groupid>0 = группа «РОВНО ОДИН предмет из N», веса = ChanceOrQuestChance. shared есть ТОЛЬКО у creature_loot_template; shared=1 = доп. проверка ~0.5% (НЕ «общий на группу» как в TC). item<0 = валюта (id = abs(item)). mincountOrRef<0 = ссылка на reference_loot_template. ChanceOrQuestChance>=100 = всегда; <0 = только для квеста. Экипируемого выпадает макс 1, неэкипируемого макс 3. У zone_loot_template есть ClassificationMask (uint8). После: .reload creature_loot_template или .reload all loot.","loot лут creature_loot_template groupid shared reference_loot_template zone_loot_template drop дроп валюта sql шаблон nordrassil 7.3.5"},
        {"SQL-шаблон: статы предмета (item_sparse, Legion)","Статы предметов в Legion живут в hotfixes.item_sparse, НЕ в world.item_template. Правка существующего предмета: UPDATE item_sparse SET ItemLevel=@ILVL, RequiredLevel=@REQLEVEL, StatModifierBonusStat1=@STAT1_TYPE, ItemStatValue1=@STAT1_VAL, StatModifierBonusStat2=@STAT2_TYPE, ItemStatValue2=@STAT2_VAL WHERE ID=@ITEM. Типы статов (StatModifierBonusStatN) сверяй по ItemStat.db2: 4=Agility, 5=Intellect, 7=Stamina, 32=Crit, 36=Haste, 40=Versatility, 49=Mastery. ВАЖНО: НОВЫЙ предмет одним SQL не делается — имя/ItemLevel/статы/сокеты клиент берёт из DB2/DBCache; в дампе Nordrassil item_bonus/scaling_stat_distribution/curve ПУСТЫЕ, нужен патч клиентских DB2 (item.db2, item-sparse.db2, spell.db2). Для правки СУЩЕСТВУЮЩЕГО предмета обычно достаточно item_template + item_sparse. hotfixes не reload-ится — после правки рестарт ядра.","item предмет статы item_sparse hotfixes itemlevel StatModifierBonusStat ItemStatValue db2 dbcache sql шаблон legion 7.3.5"},
        {"SQL-шаблон: маршрут NPC (waypoints / waypoint_data, 7.3.5)","В 7.3.5 три системы путей. (1) waypoints — для SmartAI WP_START(53): entry = path ID (НЕ entry моба!), pointid с 1: INSERT INTO waypoints (entry,pointid,position_x,position_y,position_z,point_comment) VALUES (@PATH_ID,1,@X,@Y,@Z,'т1'),(@PATH_ID,2,@X2,@Y2,@Z2,'т2'); в smart_scripts action 53 (WP_START), action_param1=@PATH_ID. (2) waypoint_data — путь по GUID спавна: id = GUID существа; INSERT INTO waypoint_data (id,point,position_x,position_y,position_z,orientation,delay,delay_chance,move_flag,speed,action,action_chance,entry,wpguid) VALUES (@GUID,1,@X,@Y,@Z,0,0,0,0,0,0,100,0,0),(@GUID,2,@X2,@Y2,@Z2,0,3000,0,0,0,0,100,0,0); привязка: UPDATE creature_addon SET path_id=@GUID WHERE guid=@GUID; и creature.MovementType=2 (иначе бродит/стоит). (3) script_waypoint — для C++ скриптов. MovementType: 0=стоит, 1=блуждание (spawndist>0), 2=путь. В master вместо waypoints/waypoint_data — waypoint_path. После: .reload waypoint_data / .reload waypoints или рестарт.","waypoint маршрут путь waypoints waypoint_data path_id movementtype creature_addon smartai wp_start sql шаблон npc 7.3.5"},
        {"SQL-шаблон: подземелье/инстанс (Nordrassil 7.3.5)","Создание данжа/рейда. (1) instance_template: INSERT INTO instance_template (map,parent,script,allowMount,bonusChance) VALUES (@MAP,0,'',0,0); map = ID карты из Map.db2. (2) Босс/энкаунтер instance_encounters: INSERT INTO instance_encounters (entry,difficulty,creditType,creditEntry,lastEncounterDungeon,comment) VALUES (@ENCOUNTER_ID,@DIFF,0,@BOSS,@MAP,'босс'); difficulty 0=5чел, 3=10чел, 4=25чел. (3) Вход access_requirement: INSERT INTO access_requirement (mapId,difficulty,dungeonId,level_min,level_max,item_level,item,item2,quest_done_A,quest_done_H,completed_achievement,completed_achievement_A,quest_failed_text,comment) VALUES (@MAP,@DIFF,0,110,0,900,0,0,0,0,0,0,NULL,'вход'). (4) Саммоны босса creature_summon_groups (summonerId,id,summonerType,groupId,entry,position_x,position_y,position_z,orientation,count,actionType,distance,summonType,summonTime). (5) Активация боссов creature_ai_instance (entry,bossid,bossidtoactivete,instanceId,comments). Логика боя — в C++ скриптах ядра (scripts/) и SmartAI босса. instance_template / instance_encounters / creature_ai_instance — рестарт ядра (не reload).","dungeon raid подземелье рейд инстанс instance_template instance_encounters access_requirement creature_summon_groups creature_ai_instance map sql шаблон 7.3.5"},
        {"SQL-шаблон: способность/каст по SmartAI (smart_scripts, 7.3.5)","Каст способности через SmartAI. Колонки: entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1..4, action_type, action_param1..6, target_type, target_param1..3, target_x, target_y, target_z, target_o, comment. Пример — каст по цели в бою: event_type=0 (UPDATE_IC; params initialMin,initialMax,repeatMin,repeatMax), action_type=11 (CAST), action_param1=@SPELL_ID, target_type=2 (VICTIM): INSERT INTO smart_scripts (...) VALUES (@MOB,0,@ID,0,0,0,100,0,3000,5000,9000,12000,11,@SPELL,0,0,0,0,0,2,0,0,0,0,0,0,0,'каст по цели'). source_type: 0=creature_template(entry), 1=GO, 2=areatrigger, 5=quest, 9=timed_actionlist. Для одного спавна — отрицательный guid в entryorguid. AIName в creature_template должен быть 'SmartAI'. PK (entryorguid,source_type,id,link). ID событий/действий сверяй по SmartScriptMgr.h своего ядра (базовые совпадают 7.3.5↔master, расширенные различаются). После: .reload smart_scripts.","smartai smart_scripts способность каст spell cast event_type action_type target_type victim update_ic sql шаблон 7.3.5 nordrassil"},
        {"Мастера SQL в Studio: готовые шаблоны","Во вкладке «Мастера SQL» есть встроенные шаблоны (кнопка «Сгенерировать SQL» подставляет значения вместо @ТОКЕНОВ): лут (независимый и группа «один из N»), текст квеста ruRU (quest_template_locale), цель квеста «убить N мобов» (quest_objectives), маршрут SmartAI (waypoints), путь по GUID (waypoint_data), статы предмета (item_sparse), каст по SmartAI (smart_scripts). Полные шаблоны с проверками и комментариями — в файлах sql/01_quests.sql … 06_abilities.sql (загружаются кнопкой «Загрузить файл»). Шаблоны НЕ обязательны для работы: вкладка «Скриптинг» генерирует SmartAI-SQL сама. Все шаблоны сверены со схемой Nordrassil 7.3.5; для другого ядра сверяй имена колонок по DESCRIBE.","мастера sql шаблоны wizards скриптинг smartai loot quest waypoint item_sparse smart_scripts studio шаблон"},
        {"Патч клиента: DB2/DBCache (WDBX Editor)","В Legion (7.3.5) и retail клиент хранит данные предметов/спеллов в DB2-файлах (и кэше DBCache.bin), а не только в серверной БД. Чтобы НОВЫЙ предмет/спелл появился в игре, одного SQL мало — нужно пропатчить клиент. Инструмент: WDBX Editor (открывает DBC/DB2/WDB/ADB Legion). Порядок: (1) отредактировать серверные таблицы (world.item_template / creature_template_spell + hotfixes.item_sparse, item_effect, spell, spell_effect). (2) Открыть в WDBX Editor соответствующие DB2 из папки клиента (DBFilesClient): item.db2, item-sparse.db2, item-effect.db2, spell.db2, spell-effect.db2, spell-aura-options.db2 и пр. (3) Добавить/изменить строки с ТЕМИ ЖЕ ID, что и на сервере. (4) Сохранить DB2 — клиент перечитает их (или обновить DBCache). (5) Для раздачи патча другим игрокам — MPQ/CASC-патч или замена файлов. ВАЖНО: ID предмета/спелла должны совпадать в world, hotfixes и клиентских DB2, иначе клиент не отобразит контент или вылетит. В дампе Nordrassil hotfixes почти пустой — основной объём клиент берёт из своих DB2.","db2 dbcache wdbx editor клиент патч client item.db2 item-sparse.db2 spell.db2 legion 7.3.5 новый предмет спелл casc mpq"},
        {"Новый предмет в Legion 7.3.5: полный цикл","Чтобы новый предмет работал и отображался: (1) world.item_template — entry (ID), class, subclass, displayid, InventoryType, AllowableClasses, Flags. (2) hotfixes.item_sparse — ItemLevel, RequiredLevel, InventoryType, качество, ItemStatValue1..10 + StatModifierBonusStat1..10, SocketType1..3. (3) Клиентские DB2 (WDBX Editor): item.db2 + item-sparse.db2 с тем же ID. (4) Лут/вендор/квест-связи в world (creature_loot_template, npc_vendor, quest_reward). (5) Иконка: DisplayInfoID → ItemDisplayInfo.db2 / texture. Без клиентского DB2 предмет будет «красным»/неизвестным или клиент вылетит. Правка СУЩЕСТВУЮЩЕГО предмета часто обходится item_template + item_sparse без DB2, если не меняются отображаемые поля. hotfixes не reload-ится — рестарт ядра; клиентские DB2 — перезапуск клиента.","новый предмет item_template item_sparse db2 wdbx displayid itemlevel legion 7.3.5 цикл loot vendor иконка"},
        {"Как определить ядро и что сверять (методика)","Перед любым SQL/скриптом определи ТОЧНУЮ ветку ядра — от неё зависят схема, ID SmartAI и команды reload. Что смотреть в исходниках ядра: (1) SmartAI ID — src/server/game/AI/SmartScripts/SmartScriptMgr.h (enum SMART_EVENT / SMART_ACTION / SMART_TARGET). (2) Команды reload — scripts/Commands/cs_reload.cpp. (3) Схема БД — DDL (SHOW CREATE TABLE) именно твоей базы. (4) Версия клиента — worldserver.conf / revision.h. НЕ переноси smart_scripts и SQL между ветками без сверки: базовые ID действий (TALK=1, CAST=11, SUMMON=12, WP_START=53, ADD_AURA=75) совпадают, но расширенные диапазоны и часть событий различаются. Для Nordrassil 7.3.5 сверяй по его SmartScriptMgr.h; для retail — по TrinityCore master. Если ядро — кастомный форк (как Nordrassil), часть логики (лут, статы) может быть переписана — читай LootMgr.cpp и аналогичные.","ядро core определить версия smartscriptmgr.h cs_reload.cpp схема ddl smartai id не переносимы методика nordrassil master"},
        {"Семейства схем ядер: 3.3.5 / Legion 7.3.5 / retail master","Три основных семейства схем TrinityCore-линии. (1) 3.3.5a (WotLK; TrinityCore 3.3.5 / AzerothCore): smart_scripts БЕЗ event_param5 (только param1–4); текст квеста прямо в quest_template, локали в locales_quest; нет hotfixes; лут creature_loot_template без Legion-семантики shared. (2) Legion 7.3.5 (Nordrassil и форки): smart_scripts с event_param1–6; квесты quest_template + quest_objectives + quest_template_locale; статы в hotfixes.item_sparse; кастомный LootMgr (groupid = один-из-N, shared=1 ≈ доп. проверка 0.5%); клиентские DB2 обязательны для нового контента. (3) retail master (10.x–12.x): quest_template + quest_objectives + quest_locale + quest_greeting; waypoint_path вместо waypoints/waypoint_data; scene_template, criteria_data, rbac; 98 reload-команд. Официальные ветки в репозитории TrinityCore: только 3.3.5, cata_classic, wotlk_classic, master. Всегда сверяй имена колонок по DESCRIBE своей базы.","схема 3.3.5 wotlk azerothcore legion 7.3.5 retail master 10.x 11.x 12.x quest_locale waypoint_path event_param5 hotfixes семейство"},
        {"Ядра 8.x–10.x (BFA/Shadowlands/Dragonflight) и CypherCore","Для 8.x (Battle for Azeroth), 9.x (Shadowlands), 10.x (Dragonflight) ОФИЦИАЛЬНЫХ веток в репозитории TrinityCore нет — только master (он покрывает retail-линию 10.x–12.x). Ядра этих версий — community-форки (как Nordrassil для 7.3.5); их схема и ID SmartAI могут отличаться от master — сверяй по исходникам конкретного форка (SmartScriptMgr.h, DDL). Структурно они ближе к master, чем к 3.3.5: квесты через quest_objectives, статы в hotfixes, клиентские DB2 обязательны для нового контента. CypherCore — ядро на C# (не C++), структурно отличается: другие имена таблиц/полей и своя логика, SQL от TrinityCore-линии напрямую не переносится. AzerothCore — форк TC 3.3.5 (WotLK), схема как 3.3.5a, местами расширена (event_param5 есть). Вывод: для любого ядра, кроме Nordrassil 7.3.5 и TC master, проверяй схему и ID по его исходникам, не копируй SQL вслепую.","8.x 9.x 10.x bfa shadowlands dragonflight cyphercore c# azerothcore 3.3.5 community форк ядро схема smartai"},
        {"Триггеры квестов и событий (SmartAI, conditions, spell_script_names)","Многие квесты и события запускаются не кнопкой, а ТРИГГЕРОМ. Основные механизмы: (1) SmartAI-события как триггеры: SPELLHIT(8) — по попаданию заклинания; ON_SPELLCLICK(73) — клик заклинанием по NPC; GOSSIP_SELECT(62) — выбор пункта диалога; QUEST_ACCEPTED — взятие квеста; UPDATE_IC(0)/UPDATE_OOC(1) — в бою / вне боя; AGGRO(4), DEATH(6). source_type: 0=creature, 1=gameobject, 2=areatrigger, 5=quest, 6=spell, 9=timed_actionlist. (2) Применение предмета: item_template.spellid_1..5 кастует спелл → спелл уходит в spell_script_names (C++-скрипт) или в SmartAI source_type=6. (3) Таблица conditions — условия на лут/квесты/спеллы. (4) Взаимодействие с NPC: gossip_menu + gossip_menu_option → действие или выдача квеста. (5) Объекты: gameobject type=2 (QUEST) привязывается к квесту. Диагностика во вкладке «Редактор контента»: «Проверить NPC» показывает триггеры smart_scripts и выдаваемые квесты; «Проверить квест» — привязки creature_queststarter/questender, цели quest_objectives и выпадение предметов цели.","триггер trigger smartai spellhit on_spellclick gossip_select quest_accepted conditions spell_script_names item spellid source_type квест событие диагностика"}
    };
    // Квестовый дроп: почему на NPC нет подсказки и как это чинится.
    { KnowledgeEntry kb{
        "Квестовый дроп предмета: почему нет подсказки на NPC",
        "Чтобы клиент понимал, что с NPC падает квестовый предмет, нужно три условия. "
        "(1) В quest_objectives у квеста должна быть строка Type=1 (ITEM) с ObjectID=<item> и Amount>0 — именно ITEM-цель даёт счётчик «0/N» и метку квестового предмета в луте; Type=0 (MONSTER) — это цель «убить», она подсвечивает NPC, но не дроп. "
        "(2) В creature_loot_template entry=<NPC> должна быть строка item=<item>: ChanceOrQuestChance<0 = дроп только пока квест активен (рекомендуется для квестовых), >0 = обычный шанс; maxcount обычно 1. "
        "(3) Предмет должен существовать в клиенте (item/item-sparse DB2) — иначе клиент не покажет ни тултип, ни метку. "
        "Важно: «искра»/подсветка на NPC для loot-целей — клиентская функция; при корректной ITEM-цели и луте предмет появится в окне лута с иконкой квеста и трекер увеличится, но отдельной подсказки при наведении на NPC для loot-целей может и не быть (в отличие от kill-целей, где NPC подсвечивается). "
        "Проверка в Studio: «Редактор контента → Проверить квест <ID>». После правок: .reload quest_template, .reload locales_quest, .reload creature_loot_template (или .reload all loot) и релог клиента.",
        "quest квест дроп loot item objective npc подсказка indicator quest_objectives creature_loot_template"
    };
        bool kbExists=false; for(const auto &c:m_entries) if(c.title==kb.title){kbExists=true;break;}
        if(!kbExists) m_entries.append(kb);
    }
    // creature_questitem — клиентская подсветка NPC и прогресс в тултипе.
    { KnowledgeEntry qi{
        "creature_questitem: подсветка NPC и прогресс 0/N в тултипе",
        "Чтобы клиент (Legion 7.3.5+) ПОДСВЕЧИВАЛ NPC и показывал в тултипе (имя/тип/уровень) прогресс «0/N» для квестового предмета, нужна запись в creature_questitem, связывающая entry NPC и item. Сама по себе ITEM-цель (quest_objectives Type=1) и лут дают дроп и счётчик в журнале, но НЕ подсвечивают NPC. "
        "Проверка: SELECT * FROM creature_questitem WHERE Item=<item>; Лечение: INSERT INTO creature_questitem (CreatureEntry, Idx, Item) VALUES (<entry_npc>, 0, <item>); (имена колонок сверь по DESCRIBE creature_questitem — встречаются CreatureEntry/Idx/Item или ItemId в AzerothCore). Если таблицы нет в дампе — ядро TrinityCore-линии всё равно грузит её при старте: создай CREATE TABLE creature_questitem (CreatureEntry INT UNSIGNED NOT NULL, Idx INT UNSIGNED NOT NULL, Item INT UNSIGNED NOT NULL, VerifiedBuild INT DEFAULT NULL, PRIMARY KEY(CreatureEntry,Idx)); затем INSERT и РЕСТАРТ worldserver (не reload) + релог клиента. "
        "После вставки — .reload creature_questitem (если есть команда) или рестарт worldserver, и ОБЯЗАТЕЛЬНО релог клиента (клиент кэширует данные NPC). Для игровых объектов аналог — gameobject_questitem. Если таблицы creature_questitem в ядре нет — проверь старый механизм: колонки creature_template.QuestItem1..QuestItem6 (присутствуют даже в 3.3.5): UPDATE creature_template SET QuestItem1=<item> WHERE entry=<npc>; затем .reload creature_template и релог. Если и их нет (как в Nordrassil: в world и hotfixes нет creature_questitem) — на Legion привязка хранится в клиентских DB2 (CreatureQuestItem.db2) и правится через WDBX; серверный обход — kill-цель (Type=0).",
        "creature_questitem gameobject_questitem подсветка npc тултип прогресс quest item клиент legion 7.3.5"
    };
        bool qiExists=false; for(const auto &c:m_entries) if(c.title==qi.title){qiExists=true;break;}
        if(!qiExists) m_entries.append(qi);
    }
    // WDBX Editor: пошаговое руководство.
    { KnowledgeEntry wx{
        "WDBX Editor: как патчить клиентские DB2 (Legion)",
        "WDBX Editor открывает DBC/DB2/WDB/ADB клиента Legion. Порядок: (1) File → Open → выбери .db2 из DBFilesClient; (2) добавь/измени строки, ID обязаны совпадать с world/hotfixes; (3) File → Save; (4) обнови DBCache.bin при необходимости; (5) перезапусти клиент. "
        "Под задачи: новый/правка предмета — item.db2, item-sparse.db2 (ItemLevel, качество, ItemStatValue1..10 + StatModifierBonusStat1..10, InventoryType), item-effect.db2, ItemDisplayInfo.db2 (иконка); новый спелл — spell.db2, spell-effect.db2, spell-aura-options.db2; привязка NPC→квестовый предмет (подсветка, 0/N в тултипе) — CreatureQuestItem.db2 (если файла нет — серверный обход kill-цель Type=0). "
        "Типы статов: 4=Agility,5=Intellect,7=Stamina,32=Crit,36=Haste,40=Versatility,49=Mastery. ID в world, hotfixes и DB2 должны совпадать, иначе клиент не отобразит контент или вылетит. Hotfixes не reload-ится — рестарт ядра; DB2 — перезапуск клиента. В Studio: «Редактор контента → WDBX / патч клиента» собирает инструкцию под задачу.",
        "wdbx editor db2 dbcache клиент патч item.db2 item-sparse.db2 spell.db2 creaturequestitem legion 7.3.5"
    };
        bool wxExists=false; for(const auto &c:m_entries) if(c.title==wx.title){wxExists=true;break;}
        if(!wxExists) m_entries.append(wx);
    }
    // Опыт: квест «используй спелл на NPC» не засчитывается (quest credit через SmartAI).
    { KnowledgeEntry qc{
        "Квест «используй спелл на NPC» не засчитывается: механика quest credit",
        "Если задача квеста «примени спелл X на NPC», а цель в quest_objectives = MONSTER (убить), каст не даёт кредита, пока нет обработчика. Официальная механика TrinityCore (issue #17098, квест Thirst Unending): NPC вешают AIName='SmartAI' и smart_scripts: event_type=8 (SPELLHIT), event_param1=<ID_спелла>, event_flags=1 (без повтора), action_type=11 (CAST), action_param1=<credit-спелл>, target_type=7 (ACTION_INVOKER) — NPC кастует на игрока кредит-спелл, тот засчитывает цель. "
        "Credit-спелл ищут в hotfixes.spell_effect по misc-колонке, равной entry NPC; ИМЯ колонки различается по веткам (EffectMiscValue / EffectMiscValue1 / MiscValue) — сначала SHOW COLUMNS FROM hotfixes.spell_effect. Если кредит-спелла в дампе нет — его создание требует hotfixes + клиентских DB2; тогда надёжный обход для багованного квеста: DELETE FROM quest_objectives WHERE QuestID=<id> (квест сдаётся сразу). "
        "Уроки: (1) не выполнять SQL с плейсхолдерами <...> — их надо заменить числами; (2) имена колонок hotfixes/spell_effect и creature_template (Name→creature_template_locale) различаются — всегда сверяй SHOW COLUMNS; (3) отсутствие ScriptName/SmartAI у NPC = каст не засчитается.",
        "quest credit smartai spellhit каст засчитывает thirst unending arcane torrent quest_objectives spell_effect misc плейсхолдер show columns"
    };
        bool qcExists=false; for(const auto &c:m_entries) if(c.title==qc.title){qcExists=true;break;}
        if(!qcExists) m_entries.append(qc);
    }
    bool changed=false;for(const auto &entry:defaults){bool exists=false;for(const auto &current:m_entries)if(current.title==entry.title){exists=true;break;}if(!exists){m_entries.append(entry);changed=true;}}if(changed)save(nullptr);
}
static QStringList tokens(const QString &s){return s.toLower().split(QRegularExpression("[^\\p{L}\\p{N}_]+"),Qt::SkipEmptyParts);}
QString KnowledgeBase::search(const QString &query,int maxEntries,int maxChars) const {
    const auto q=tokens(query);QVector<QPair<int,int>> ranking;for(int i=0;i<m_entries.size();++i){const auto body=(m_entries[i].title+" "+m_entries[i].tags+" "+m_entries[i].text).toLower();int score=0;for(const auto &t:q)if(t.size()>2)score+=body.count(t);if(score)ranking.append({score,i});}
    std::sort(ranking.begin(),ranking.end(),[](auto a,auto b){return a.first>b.first;});QString result;for(int n=0;n<ranking.size()&&n<maxEntries;++n){const auto &e=m_entries[ranking[n].second];QString part="## "+e.title+"\n"+e.text+"\n";if(result.size()+part.size()>maxChars)break;result+=part;}return result;
}
